name: tododuo
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  image_picker: ^1.2.0
  firebase_storage: ^13.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
