// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9B6aSUWa7sDSAjuLsCxkPz-MzVZ1CavY',
    appId: '1:253897393155:web:ceb1e6b26e6223021bfa36',
    messagingSenderId: '253897393155',
    projectId: 'tododuo-24',
    authDomain: 'tododuo-24.firebaseapp.com',
    storageBucket: 'tododuo-24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_iIooeEjtVuMGd-P-tG9T03ZXdOtl0vQ',
    appId: '1:253897393155:android:4321d2f3851c9dd71bfa36',
    messagingSenderId: '253897393155',
    projectId: 'tododuo-24',
    storageBucket: 'tododuo-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgOYcegQZJvvtgP1MmPH3Fus-ZcuKrhBo',
    appId: '1:253897393155:ios:377cf37b488be6901bfa36',
    messagingSenderId: '253897393155',
    projectId: 'tododuo-24',
    storageBucket: 'tododuo-24.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

}